 # Plantilla de configuraci\u00f3n (Segura para subir a GitHub)
# Plantilla de configuraci\u00f3n (Segura para subir a GitHub)
db.url=jdbc:postgresql://localhost:5432/mibasedatos
db.user=TU_USUARIO_AQUI
db.password=TU_CONTRASE\u00d1A_AQUI
api.sendemail.key=TU_API_KEY_AQUI