package form;

import cruddemo.ClientService;
import cruddemo.SessionService;
import cruddemo.UserService;
import entity.Client;
import entity.Session;
import entity.User;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johans caicedo
 */
public class AdminForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminForm.class.getName());
    protected Session session;
    protected SessionService sessionservice;

    /**
     * *
     *
     *
     * @param s
     *
     */
    public AdminForm(Session s) {

        sessionservice = new SessionService();

        if (!sessionservice.checkSession(s)) {//session iniciada
            initComponents();
            this.session = sessionservice.getSession(s);

            if ("operator".equals(s.getUser().getRol())) {
                buttonCreateUsr.setEnabled(false);
                buttonListUser.setEnabled(false);
            }
            if (s.getUser() != null) {

                labeluser.setText("Administrador de usuarios: "
                        + s.getUser().getRol());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeluser = new javax.swing.JLabel();
        buttonListUser = new javax.swing.JButton();
        buttonListClient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        buttonCreateClient = new javax.swing.JButton();
        buttonBuscarClient = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        buttonCreateUsr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labeluser.setText("Administrador de usuarios");

        buttonListUser.setText("Listar usuarios");
        buttonListUser.addActionListener(this::buttonListUserActionPerformed);

        buttonListClient.setText("Listar clientes");
        buttonListClient.addActionListener(this::buttonListClientActionPerformed);

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableResult);

        buttonCreateClient.setText("Crear cliente");
        buttonCreateClient.addActionListener(this::buttonCreateClientActionPerformed);

        buttonBuscarClient.setText("Buscar cliente");
        buttonBuscarClient.addActionListener(this::buttonBuscarClientActionPerformed);

        jTextField1.setText(" ");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });

        buttonCreateUsr.setText("Crear usuario");
        buttonCreateUsr.addActionListener(this::buttonCreateUsrActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonListClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonListUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labeluser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCreateClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBuscarClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(buttonCreateUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labeluser)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonListUser)
                        .addGap(18, 18, 18)
                        .addComponent(buttonListClient)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCreateClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCreateUsr)
                        .addGap(9, 9, 9)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuscarClient))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonListClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListClientActionPerformed
        // TODO add your handling code here:

        String[] columnas = {"ID", "Nombre", "clave", "correo", "saldo", "Editar", "Borrar"};
        DefaultTableModel table = new DefaultTableModel(null, columnas);
        tableResult.setModel(table);

        ClientService clientService = new ClientService();
        List<Client> clients = clientService.listClients();

        System.out.println(clients.size());
        for (int i = 0; i < clients.size(); i++) {
            Object[] row = new Object[7];
            row[0] = clients.get(i).getId();
            row[1] = clients.get(i).getName();
            row[2] = clients.get(i).getPassword();
            row[3] = clients.get(i).getCorreo();
            row[4] = clients.get(i).getSaldo();
            JButton editar = new JButton("Editar");

            JButton borrar = new JButton("Borrar");
            row[5] = editar;
            row[6] = borrar;
            System.out.println(row[0] + "-" + row[1] + "-" + row[2] + "-" + row[3] + "-" + row[4]);

            table.addRow(row);
        }
        sessionservice.setQuery(session.getUser(), new Date(), clientService.getClass() + "createClient() list clients");
    }//GEN-LAST:event_buttonListClientActionPerformed

    private void buttonListUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListUserActionPerformed
        // TODO add your handling code here:
        String[] columnas = {"ID", "Nombre", "clave", "correo"};
        DefaultTableModel table = new DefaultTableModel(null, columnas);
        tableResult.setModel(table);

        UserService userService = new UserService();
        List<User> users = userService.listUsers();

        System.out.println(users.size());
        for (int i = 0; i < users.size(); i++) {
            Object[] row = new Object[5];
            row[0] = users.get(i).getId();
            row[1] = users.get(i).getUser();
            row[2] = users.get(i).getPwd();
            row[3] = users.get(i).getEmail();

            System.out.println(row[0] + "-" + row[1] + "-" + row[2] + "-" + row[3]);

            table.addRow(row);
        }

        sessionservice.setQuery(session.getUser(), new Date(), userService.getClass() + "createClient() list users");
    }//GEN-LAST:event_buttonListUserActionPerformed

    private void buttonCreateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateClientActionPerformed
        // TODO add your handling code here:

        if (false == sessionservice.checkSession(session)) {
            buttonCreateClient.setEnabled(false);
        }
        CreateClient createClient = new CreateClient(session);
        createClient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonCreateClientActionPerformed

    private void buttonBuscarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarClientActionPerformed
        // TODO add your handling code here:

        String[] columnas = {"ID", "Nombre", "clave", "correo", "saldo", "Editar", "Borrar"};
        DefaultTableModel table = new DefaultTableModel(null, columnas);
        tableResult.setModel(table);

        String nombre = jTextField1.getText();
        ClientService clientService = new ClientService();
        List<Client> clients = clientService.findClient(nombre);

        System.out.println(clients.size());
        if (clients.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado!");
        }
        for (int i = 0; i < clients.size(); i++) {
            Object[] row = new Object[7];
            row[0] = clients.get(i).getId();
            row[1] = clients.get(i).getName();
            row[2] = clients.get(i).getPassword();
            row[3] = clients.get(i).getCorreo();
            row[4] = clients.get(i).getSaldo();
            JButton editar = new JButton("Editar");

            JButton borrar = new JButton("Borrar");
            row[5] = editar;
            row[6] = borrar;
            System.out.println(row[0] + "-" + row[1] + "-" + row[2] + "-" + row[3] + "-" + row[4]);

            table.addRow(row);
        }
        sessionservice.setQuery(session.getUser(), new Date(), clientService.getClass() + "createClient() find users");
    }//GEN-LAST:event_buttonBuscarClientActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void buttonCreateUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateUsrActionPerformed
        // TODO add your handling code here:

//        if (false == sessionservice.checkSession(session)) {
//            buttonCreateUsr.setEnabled(false);
//        }
        CreateUser createUser = new CreateUser(session);
        createUser.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_buttonCreateUsrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarClient;
    private javax.swing.JButton buttonCreateClient;
    private javax.swing.JButton buttonCreateUsr;
    private javax.swing.JButton buttonListClient;
    private javax.swing.JButton buttonListUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labeluser;
    private javax.swing.JTable tableResult;
    // End of variables declaration//GEN-END:variables
}
