package form;

import cruddemo.ClientService;
import cruddemo.SessionService;
import cruddemo.UserService;
import entity.Client;
import entity.Session;
import entity.User;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.function.Consumer;

/**
 *
 * @author johans caicedo
 */
public class AdminForm extends javax.swing.JFrame {

    protected Session session;
    protected SessionService sessionservice;

    /**
     * *
     *
     *
     * @param s
     * <p>
     * Session</p>
     *
     */
    public AdminForm(Session s) {

        sessionservice = new SessionService();

        if (!sessionservice.checkSession(s)) {//session iniciada

            initComponents();
            this.session = sessionservice.getSession(s);

            if ("operator".equals(s.getUser().getRol())) {
                buttonCreateUsr.setEnabled(false);
                buttonListUser.setEnabled(false);
                buttonAuditar.setEnabled(false);
            }

            if ("auditor".equals(s.getUser().getRol())) {
                buttonCreateClient.setEnabled(false);
                buttonCreateUsr.setEnabled(false);
            }
            if (s.getUser() != null) {

                labeluser.setText("Administrador de usuarios: "
                        + s.getUser().getRol());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeluser = new javax.swing.JLabel();
        buttonListUser = new javax.swing.JButton();
        buttonListClient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        buttonCreateClient = new javax.swing.JButton();
        buttonBuscarClient = new javax.swing.JButton();
        fieldCliente = new javax.swing.JTextField();
        buttonCreateUsr = new javax.swing.JButton();
        buttonAuditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labeluser.setText("Administrador de usuarios");

        buttonListUser.setText("Listar usuarios");
        buttonListUser.addActionListener(this::buttonListUserActionPerformed);

        buttonListClient.setText("Listar clientes");
        buttonListClient.addActionListener(this::buttonListClientActionPerformed);

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableResult);

        buttonCreateClient.setText("Crear cliente");
        buttonCreateClient.addActionListener(this::buttonCreateClientActionPerformed);

        buttonBuscarClient.setText("Buscar cliente");
        buttonBuscarClient.addActionListener(this::buttonBuscarClientActionPerformed);

        fieldCliente.setText(" ");
        fieldCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldClienteFocusGained(evt);
            }
        });

        buttonCreateUsr.setText("Crear usuario");
        buttonCreateUsr.addActionListener(this::buttonCreateUsrActionPerformed);

        buttonAuditar.setText("Auditar");
        buttonAuditar.addActionListener(this::buttonAuditarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonListClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonListUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labeluser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCreateClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBuscarClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldCliente)
                    .addComponent(buttonCreateUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAuditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labeluser)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonListUser)
                        .addGap(18, 18, 18)
                        .addComponent(buttonListClient)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCreateClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCreateUsr)
                        .addGap(9, 9, 9)
                        .addComponent(fieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuscarClient)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAuditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * *
     *
     *
     * @param evt
     * <p>
     * instancias del evento</p>
     */
    private void buttonListClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListClientActionPerformed

        // 1. Definir columnas incluyendo Editar y Borrar
        String[] columnas = {"ID", "Nombre", "Clave", "Correo", "Saldo", "Editar", "Borrar"};

        DefaultTableModel tableModel = new DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // ¡Importante! Las columnas 5 y 6 (los botones) deben ser editables para que funcionen
                return column == 5 || column == 6;
            }
        };
        tableResult.setModel(tableModel);

        ClientService clientService = new ClientService();
        //List<Client> clients = clientService.listClients();

        List<Client> clients = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            
            clients.add(new Client());
        }
        
//        if (clients == null || clients.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "No hay clientes registrados.");
//            return;
//        }

        // 2. Llenar los datos de los clientes y el texto de los botones ("Editar" / "Borrar")
        for (Client client : clients) {
            Object[] row = new Object[7];
            row[0] = client.getId();
            row[1] = client.getName();
            row[2] = client.getPassword();
            row[3] = client.getCorreo();
            row[4] = client.getSaldo();
            row[5] = "Editar";   // Texto que mostrará el botón de la columna 5
            row[6] = "Borrar";   // Texto que mostrará el botón de la columna 6

            tableModel.addRow(row);
        }

        // 3. Asignar el Renderizador y el Editor a la columna 5 (Editar)
        tableResult.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer());
        tableResult.getColumnModel().getColumn(5).setCellEditor(new ButtonEditor(new JCheckBox(), rowClicked -> {
            // ACCIÓN CUANDO HACEN CLIC EN EDITAR
            int clientId = (int) tableResult.getValueAt(rowClicked, 0); // Obtener ID de la fila
            String clientName = (String) tableResult.getValueAt(rowClicked, 1);

            JOptionPane.showMessageDialog(this, "Editar cliente ID: " + clientId + " - " + clientName);
            // Aquí puedes abrir tu formulario de edición pasando el ID
        }));

        // 4. Asignar el Renderizador y el Editor a la columna 6 (Borrar)
        tableResult.getColumnModel().getColumn(6).setCellRenderer(new ButtonRenderer());
        tableResult.getColumnModel().getColumn(6).setCellEditor(new ButtonEditor(new JCheckBox(), rowClicked -> {
            // ACCIÓN CUANDO HACEN CLIC EN BORRAR
            int clientId = (int) tableResult.getValueAt(rowClicked, 0);

            int confirm = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar al cliente con ID: " + clientId + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Lógica para borrar en base de datos y refrescar la tabla
                JOptionPane.showMessageDialog(this, "Cliente eliminado con éxito.");
                buttonListClientActionPerformed(null); // Refrescar lista
            }
        }));

    }//GEN-LAST:event_buttonListClientActionPerformed

    /**
     * *
     *
     *
     * @param evt
     * <p>
     * Instancias del evento</p>
     *
     */
    private void buttonListUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListUserActionPerformed

        String[] columnas = {"ID", "Nombre", "clave", "correo"};
        DefaultTableModel table = new DefaultTableModel(null, columnas);
        tableResult.setModel(table);

        UserService userService = new UserService();
        List<User> users = userService.listUsers();

        System.out.println(users.size());
        for (int i = 0; i < users.size(); i++) {
            Object[] row = new Object[5];
            row[0] = users.get(i).getId();
            row[1] = users.get(i).getUser();
            row[2] = users.get(i).getPwd();
            row[3] = users.get(i).getEmail();

            System.out.println(row[0] + "-" + row[1] + "-" + row[2] + "-" + row[3]);

            table.addRow(row);
        }

        sessionservice.setQuery(session.getUser(), new Date(), userService.getClass() + "createClient() list users");
    }//GEN-LAST:event_buttonListUserActionPerformed

    /**
     * *
     *
     *
     * @param evt
     * <p>
     * Instancias del evento</p>
     *
     */
    private void buttonCreateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateClientActionPerformed

        if (false == sessionservice.checkSession(session)) {
            buttonCreateClient.setEnabled(false);
        }
        CreateClient createClient = new CreateClient(session);
        createClient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonCreateClientActionPerformed

    /**
     * *
     *
     *
     * @param evt
     * <p>
     * Instancias del evento</p>
     *
     */
    private void buttonBuscarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarClientActionPerformed

        // 1. Definir columnas (sin los botones directos por ahora para evitar errores visuales)
        String[] columnas = {"ID", "Nombre", "Clave", "Correo", "Saldo"};

        // 2. Crear el modelo de la tabla y asignarlo
        DefaultTableModel tableModel = new DefaultTableModel(null, columnas) {
            // Opcional: hacer que las celdas no sean editables directamente haciendo doble clic
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableResult.setModel(tableModel);

        // 3. Consumir el servicio
        ClientService clientService = new ClientService();
        List<Client> clients = clientService.listClients();

        // Validar si la lista viene vacía o nula
        if (clients == null || clients.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay clientes registrados.");
            return;
        }

        // 4. Recorrer la lista y poblar el modelo
        for (Client client : clients) {
            Object[] row = new Object[5];
            row[0] = client.getId();
            row[1] = client.getName();
            row[2] = client.getPassword();
            row[3] = client.getCorreo();
            row[4] = client.getSaldo();

            tableModel.addRow(row);
        }

        // 5. Registrar la auditoría de la sesión
        if (session != null && session.getUser() != null) {
            sessionservice.setQuery(session.getUser(), new Date(), clientService.getClass().getName() + " -> listClients()");
        }

    }//GEN-LAST:event_buttonBuscarClientActionPerformed

    /**
     * *
     *
     *
     * @param evt
     * <p>
     * Instancias del evento</p>
     *
     */
    private void fieldClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldClienteFocusGained

        fieldCliente.setText("");
    }//GEN-LAST:event_fieldClienteFocusGained

    /**
     * *
     *
     *
     * @param evt
     * <p>
     * Instancias del evento</p>
     *
     */
    private void buttonCreateUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateUsrActionPerformed

        if (false == sessionservice.checkSession(session)) {
            buttonCreateUsr.setEnabled(false);
            CreateUser createUser = new CreateUser(session);
            createUser.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_buttonCreateUsrActionPerformed

    private void buttonAuditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAuditarActionPerformed
        // TODO add your handling code here:
        AuditorForm auditorform = new AuditorForm(session);
        auditorform.setVisible(true);
    }//GEN-LAST:event_buttonAuditarActionPerformed

    public AdminForm() throws HeadlessException {
        initComponents();
    }

    public static void main(String[] args) {
        AdminForm adminForm = new AdminForm();
        adminForm.setVisible(true);
    }

    class ButtonEditor extends DefaultCellEditor {

        protected JButton button;
        private String label;
        private boolean clicked;
        private int row;
        private Consumer<Integer> actionOnClick; // Callback para enviar el número de fila

        public ButtonEditor(JCheckBox checkBox, Consumer<Integer> actionOnClick) {
            super(checkBox);
            this.actionOnClick = actionOnClick;
            button = new JButton();
            button.setOpaque(true);
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped(); // Detiene la edición de la celda
                    if (actionOnClick != null) {
                        actionOnClick.accept(row); // Devuelve la fila seleccionada
                    }
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            this.row = row;
            label = (value == null) ? "" : value.toString();
            button.setText(label);
            clicked = true;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return label;
        }
    }

    class ButtonRenderer extends JButton implements TableCellRenderer {

        public ButtonRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText((value == null) ? "" : value.toString());
            return this;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAuditar;
    private javax.swing.JButton buttonBuscarClient;
    private javax.swing.JButton buttonCreateClient;
    private javax.swing.JButton buttonCreateUsr;
    private javax.swing.JButton buttonListClient;
    private javax.swing.JButton buttonListUser;
    private javax.swing.JTextField fieldCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeluser;
    private javax.swing.JTable tableResult;
    // End of variables declaration//GEN-END:variables
}
