package form;

import cruddemo.AuditorService;
import cruddemo.SessionService;
import entity.Movement;
import entity.Session;
import entity.User;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johans caicedo
 */
public class AuditorForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(AuditorForm.class.getName());
    protected SessionService sessionService;
    protected Session session;

    /**
     * Creates new form AuditorForm
     *
     * @param s Session
     */
    public AuditorForm(Session s) {

        sessionService = new SessionService();
        sessionService.checkSession(s);

        if (!sessionService.checkSession(s)) {//session iniciada

            initComponents();
            this.session = sessionService.getSession(s);
            if (s.getUser() != null) {

                labeluser.setText("Usuario: "+
                        s.getUser().getRol());
                this.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        labeluser = new javax.swing.JLabel();
        showLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        showMovements = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labeluser.setText("Auditor panel");

        showLogin.setText("Ver login");
        showLogin.addActionListener(this::showLoginActionPerformed);

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableResult);

        showMovements.setText("Ver movimientos");
        showMovements.addActionListener(this::showMovementsActionPerformed);

        jButton3.setText("Ver Errores");
        jButton3.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showLogin)
                    .addComponent(showMovements)
                    .addComponent(jButton3)
                    .addComponent(labeluser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labeluser)
                        .addGap(53, 53, 53)
                        .addComponent(showLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showMovements)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLoginActionPerformed

        String[] columnas = {"Id", "rol", "nombre", "clave", "correo"};
        DefaultTableModel table = new DefaultTableModel(null, columnas);
        tableResult.setModel(table);

        AuditorService auditorService = new AuditorService();
        List<User> loginUsers = auditorService.listLogin();

        for (int i = 0; i < loginUsers.size(); i++) {
            Object[] row = new Object[5];
            row[0] = loginUsers.get(i);
            row[1] = loginUsers.get(i);
            row[2] = loginUsers.get(i);
            row[3] = loginUsers.get(i);
            row[4] = loginUsers.get(i);

            System.out.println(row[0] + "-" + row[1] + "-" + row[2] + "-" + row[3]);

            table.addRow(row);
        }

        sessionService.setQuery(session.getUser(), new Date(),
                auditorService.getClass() + "list login()");

    }//GEN-LAST:event_showLoginActionPerformed

    private void showMovementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMovementsActionPerformed
         
        String[] columnas = {"Id", "Usuario", "Fecha", "Movimiento"};
        DefaultTableModel table = new DefaultTableModel(null, columnas);
        tableResult.setModel(table);

        AuditorService auditorService = new AuditorService();

        List<Movement> movements = auditorService.listMovements();

        
        for (int i = 0; i < movements.size(); i++) {
            Object[] row = new Object[4];
            row[0] = movements.get(i);
            row[1] = movements.get(i);
            row[2] = movements.get(i);
            row[3] = movements.get(i);

            System.out.println(row[0] + "-" + row[1] + "-" + row[2] + "-" + row[3]);

            table.addRow(row);
        }

        sessionService.setQuery(session.getUser(), new Date(),
                auditorService.getClass() + "listMovement()");
    }//GEN-LAST:event_showMovementsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labeluser;
    private javax.swing.JButton showLogin;
    private javax.swing.JButton showMovements;
    private javax.swing.JTable tableResult;
    // End of variables declaration//GEN-END:variables
}
