package form;

import cruddemo.ClientService;
import cruddemo.SessionService;
import entity.Client;
import entity.Session;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author johans caicedo
 */
public class CreateClient extends javax.swing.JFrame {

    protected SessionService sessionservice;
    protected Session session;
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(CreateClient.class.getName());

    /**
     * *
     *
     *
     * @param s Session
     *
     */
    public CreateClient(Session s) {

        sessionservice = new SessionService();
        if (!sessionservice.checkSession(s)) {//session iniciada
            initComponents();
            this.session = sessionservice.getSession(s);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        claveField = new javax.swing.JTextField();
        correoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        crearClientBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        montoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Crear cliente");

        nombreField.setText(" ");
        nombreField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFieldFocusGained(evt);
            }
        });

        claveField.setText(" ");
        claveField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                claveFieldFocusGained(evt);
            }
        });

        correoField.setText(" ");
        correoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoFieldFocusGained(evt);
            }
        });

        jLabel2.setText("Nombre ");

        jLabel3.setText("Clave ");

        jLabel4.setText("Correo ");

        crearClientBtn.setText("Crear ");
        crearClientBtn.addActionListener(this::crearClientBtnActionPerformed);

        jLabel5.setText("Monto");

        montoField.setText("  ");
        montoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                montoFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(crearClientBtn)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(81, 81, 81))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(91, 91, 91)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombreField)
                                .addComponent(claveField)
                                .addComponent(correoField)
                                .addComponent(montoField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))))
                    .addComponent(jLabel1))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(claveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(montoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(crearClientBtn)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClientBtnActionPerformed

        ClientService clientService = new ClientService();
        Client client = new Client();

        String nombre = nombreField.getText();
        String clave = claveField.getText();
        String correo = correoField.getText();
        int monto = 0;

        try {
            monto = Integer.parseInt(montoField.getText());

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Digite un monto valido " + monto);
        }

        /*
            TODO crear las validaciones de las entradas de datos
            Restriccciones correo(longitud, caracteres), 
            monto(intervalo, solo numeros), 
        */
        if (nombre.isBlank()
                || clave.isBlank()
                || correo.isBlank()
                || montoField.getText().isBlank()) {

            JOptionPane.showMessageDialog(null, "Campos obligatorios");
        } else {

            if (monto > 0) {

                client.setName(nombre);
                client.setPassword(clave);
                client.setCorreo(correo);
                client.setSaldo(monto);

                if (clientService.createClient(client)) {
                    JOptionPane.showMessageDialog(null, "Error al crear el cliente");
                } else {
                    JOptionPane.showMessageDialog(null, "Cliente creado");
                    nombreField.setText("");
                    claveField.setText("");
                    correoField.setText("");
                    montoField.setText("");
                }
            }
        }

        /**
         * Auditory subroutine
         *
         */
        sessionservice.setQuery(session.getUser(), new Date(),
                clientService.getClass() + "createClient()");

    }//GEN-LAST:event_crearClientBtnActionPerformed

    private void nombreFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFieldFocusGained
        // TODO add your handling code here:
        nombreField.setText("");
    }//GEN-LAST:event_nombreFieldFocusGained

    private void claveFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_claveFieldFocusGained
        // TODO add your handling code here:
        claveField.setText("");
    }//GEN-LAST:event_claveFieldFocusGained

    private void correoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoFieldFocusGained
        // TODO add your handling code here:
        correoField.setText("");
    }//GEN-LAST:event_correoFieldFocusGained

    private void montoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montoFieldFocusGained
        // TODO add your handling code here:
        montoField.setText("");
    }//GEN-LAST:event_montoFieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField claveField;
    private javax.swing.JTextField correoField;
    private javax.swing.JButton crearClientBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField montoField;
    private javax.swing.JTextField nombreField;
    // End of variables declaration//GEN-END:variables
}
