package form;

import cruddemo.ClientService;
import cruddemo.SessionService;
import entity.Client;
import entity.Session;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author johans caicedo
 */
public class CreateClient extends javax.swing.JFrame {

    protected SessionService sessionservice;
    protected Session session;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateClient.class.getName());

    /***
     * 
     * 
     * @param s Session 
     **/
    public CreateClient(Session s) {

        sessionservice = new SessionService();
        if (!sessionservice.checkSession(s)) {//session iniciada
            initComponents();
            this.session = sessionservice.getSession(s);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreFIeld = new javax.swing.JTextField();
        claveField = new javax.swing.JTextField();
        correoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        montoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Crear cliente");

        nombreFIeld.setText(" ");
        nombreFIeld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFIeldFocusGained(evt);
            }
        });

        claveField.setText(" ");
        claveField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                claveFieldFocusGained(evt);
            }
        });

        correoField.setText(" ");
        correoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoFieldFocusGained(evt);
            }
        });

        jLabel2.setText("Nombre ");

        jLabel3.setText("Clave ");

        jLabel4.setText("Correo ");

        jButton1.setText("Crear ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel5.setText("Monto");

        montoField.setText("  ");
        montoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                montoFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(81, 81, 81))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(91, 91, 91)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreFIeld)
                                    .addComponent(claveField)
                                    .addComponent(correoField)
                                    .addComponent(montoField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(claveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(montoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ClientService clientService = new ClientService();
        Client client = new Client();
        if (!"".equals(nombreFIeld.getText())) {
            client.setName(nombreFIeld.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Digite el nombre!");
        }
        if (!"".equals(claveField.getText())) {

            client.setPassword(claveField.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Digite la clave!");
        }
        if (!"".equals(correoField.getText())) {
            client.setCorreo(correoField.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Digite el correo!");
        }
        if (!"".equals(montoField.getText())) {
            JOptionPane.showMessageDialog(null, "Digite el monto!");
        }else{
            int monto = Integer.parseInt(montoField.getText());
            client.setSaldo(monto);
        }

        if (clientService.createClient(client)) {
            JOptionPane.showMessageDialog(null, "Cliente creado!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro al crear el suaurio!");
        }
        /**
         * Auditory subroutine
         *
         */
        sessionservice.setQuery(session.getUser(), new Date(),
                clientService.getClass() + "createClient()");

        AdminForm adminForm = new AdminForm(session);
        adminForm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreFIeldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFIeldFocusGained
        // TODO add your handling code here:
        nombreFIeld.setText("");
    }//GEN-LAST:event_nombreFIeldFocusGained

    private void claveFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_claveFieldFocusGained
        // TODO add your handling code here:
        claveField.setText("");
    }//GEN-LAST:event_claveFieldFocusGained

    private void correoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoFieldFocusGained
        // TODO add your handling code here:
        correoField.setText("");
    }//GEN-LAST:event_correoFieldFocusGained

    private void montoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montoFieldFocusGained
        // TODO add your handling code here:
        montoField.setText("");
    }//GEN-LAST:event_montoFieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField claveField;
    private javax.swing.JTextField correoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField montoField;
    private javax.swing.JTextField nombreFIeld;
    // End of variables declaration//GEN-END:variables
}
