package form;

import entity.Session;
import entity.User;
import cruddemo.LoginService;
import cruddemo.SessionService;
import err.Err_login;
import java.util.Date;
import java.util.logging.Logger;

/**
 *
 * @author johans caicedo
 */
public class Login extends javax.swing.JFrame {

    protected SessionService sessionService;
    protected Session session;
    private static final Logger logger = null;

    /**
     * Creates new form login
     *
     * @param session
     */
    public Login(Session session) {

        initComponents();
        if (session == null) {

            this.setVisible(true);
        } else {

            Login login = new Login(session);
            login.setVisible(true);
        }
    }

    /**
     *
     * pytrends
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameuser = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameuser.setText("user1");

        loginButton.setText("login");
        loginButton.addActionListener(this::loginButtonActionPerformed);

        password.setText("user1");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginButton)
                    .addComponent(nameuser, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(password))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(nameuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int cntLogin = 0;

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String user;
        String pasword;
        Err_login err_login = null;
        User usr = new User();

        user = nameuser.getText();
        pasword = password.getText();

        AdminForm adminform = null;
        LoginService serviceLogin = new LoginService();

        usr = serviceLogin.login(user, pasword);

        if (((usr.getUser() != null) && (usr.getPwd() != null))
                && (usr.getUser().equals(user) && usr.getPwd().equals(pasword))) {

            /*
             INICIA LA SESSION
                    Instancia la session dentro del bucle if que valida las restricciones 
                    - El usuario debe ingresar el nombre y la contraseña
                    - El servicio debe retornar una instancia de Usuario Class != null
             */
            this.session = new Session(usr);
            this.sessionService = new SessionService();
            this.sessionService.setSession(session);
        
            
            adminform = new AdminForm(this.session);
            adminform.setVisible(true);
            this.setVisible(false);
        } else {

            err_login = new Err_login();
            err_login.setErr("Usuario no encontrado");
            session = new Session(usr);
            session.setError(err_login);

            if (cntLogin >= 2) {

                this.setVisible(false);

                Resetuser resetUsr = new Resetuser(session);
                resetUsr.setVisible(true);
            } else {    

                cntLogin = cntLogin += 1;

                this.setVisible(false);

                this.setVisible(true);
                Warning prompt = new Warning(this, true, session, cntLogin);
                prompt.setVisible(true);
            }
        }
        sessionService.setQuery(session.getUser(), new Date(), serviceLogin+"login");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    public static void main(String[] args) {
        Login login = new Login(null);
        login.setVisible(true);
    }
//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField nameuser;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables

}
