package form;

import entity.Session;
import javax.swing.JOptionPane;
import com.resend.Resend;
import com.resend.core.exception.ResendException;
import com.resend.services.emails.model.CreateEmailOptions;
import com.resend.services.emails.model.CreateEmailResponse;
import cruddemo.SessionService;

/**
 *
 * @author johans caicedo
 */
public class Resetuser extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(Resetuser.class.getName());

    protected SessionService sessionservice;
    protected Session session;

    /**
     * *
     *
     *
     * @param s
     **
     */
    public Resetuser(Session s) {

        sessionservice = new SessionService();
        if (!sessionservice.checkSession(s)) {//session iniciada
            initComponents();
            this.session = sessionservice.getSession(s);
            //tittleLabel.setText(session.geterrLogin());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittleLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tittleLabel.setText("Recordar usuario");

        correoLabel.setText("Correo");

        emailField.setText(" ");

        enviarButton.setText("enviar");
        enviarButton.addActionListener(this::enviarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enviarButton)
                    .addComponent(correoLabel)
                    .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tittleLabel)
                .addGap(35, 35, 35)
                .addComponent(correoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(enviarButton)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:emailField

        String correo = emailField.getText();

        if (!"".equals(correo)) {
            Resend resend = new Resend("");

            CreateEmailOptions params = CreateEmailOptions.builder()
                    .from("onboarding@resend.dev") // Dirección por defecto para pruebas
                    .to(correo)
                    .subject("Prueba de correo desde Java")
                    .html("<h1>¡Hola desde Java!</h1><p>Este es un correo enviado con la API de Resend.</p>")
                    .build();

            try {
                // 3. Envía el correo
                CreateEmailResponse data = resend.emails().send(params);
                System.out.println("Correo enviado con éxito. ID: " + data.getId());
            } catch (ResendException e) {
                System.err.println("Error al enviar el correo: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, " " + "Digite un correo");
        }


    }//GEN-LAST:event_enviarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables
}
